### ISSUE TITLE
The button does not show up in the atto toolbar in moodle 3.9

### ISSUE THREAD

**Issue by dsoini** [Panopto/Panopto-LTI-Button-For-Atto#1]
I have installed this manually (because our system doesn't allow the server to write to the web directory) in lib/editor/atto/plugins/panoptoltibutton.

I have added it to: style1 = title, bold, italic, fontfamily, fontsize, morefontcolors, panoptoltibutton

We don't have "widget" installed. Is this required for panoptoltibutton?

I uninstalled panoptobutton in case that was causing the new plugin to not appear.

I also tried putting the panoptoltibutton in the lines for other items, such as link or files.

What am I missing? Do you have a support page for this plugin anywhere?

**Comment by jmalmsten-panopto** [comment]
Hi, 

This tool requires Moodle LTI tools to be configured for your Panopto server for the button to show up. See the below requested support document for more information:
https://support.panopto.com/s/article/How-to-Enable-Student-Submission-for-Moodle

If you have any further issues please open a ticket with Panopto support at https://support.panopto.com/

Thanks,
Joe
