### ISSUE TITLE
3.10 compatibility

### ISSUE THREAD

**Issue by phette23** [Panopto/Panopto-LTI-Button-For-Atto#3]
This project's only release is marked as compatible up to Moodle version 3.9. What is the timeline for a release compatible with 3.10? We plan to update to 3.10 this summer but we rely heavily on Panopto.

**Comment by jmalmsten-panopto** [comment]
Hi,

The latest release supports Moodle version 3.9, 3.10, and 3.11.

Thanks,
Joe Malmsten
