### ISSUE TITLE
Dropdown list looks strange if only one action is available

### ISSUE THREAD

**Issue by Syxton** [Panopto/Panopto-LTI-Button-For-Atto#5]
![image](https://github.com/Panopto/Panopto-LTI-Button-For-Atto/assets/989354/c0dd6f2d-4094-497a-b0d5-02eddbc1ee3a)

If there is only 1 visible option, it would be better to have a regular button like we see in the TinyMCE version of the plugin.

**Comment by zeroAps** [comment]
Thank you for reporting this. I will create internal item to investigate, and see if we can make improvements here.

**Comment by zeroAps** [comment]
This should be fixed in the latest version of the plugin. Closing this for now.
